require 'benchmark'
require_relative '../lib/in_order_traversal'
require_relative '../lib/quick_find'
require_relative '../lib/quick_union'

require_relative '../lib/sorting/bubble_sort'
require_relative '../lib/sorting/insertion_sort'
require_relative '../lib/sorting/quick_sort'
require_relative '../lib/sorting/merge_sort'

require_relative '../lib/data_structures/linked_list_stack'
require_relative '../lib/data_structures/dynamic_array_stack'
require_relative '../lib/data_structures/binary_tree'
require_relative '../lib/data_structures/avl_tree'
require_relative '../lib/data_structures/hash_table'
require_relative '../lib/data_structures/heap'
